-- ============================================================================
-- CREV Exam Platform — PROPOSED schema (design only — NOT executed).
--
-- This file is a DESIGN PROPOSAL generated by inspecting the application code
-- (src/services/repository.js, src/services/supabase.js, src/services/auth.js,
-- src/pages/*, src/hooks/*, supabase/*.sql). It has NOT been run against any
-- Supabase project.
--
-- Every table / column / RPC in here is backed by a real call in the code.
-- Nothing was invented. Anything ambiguous is flagged in REPORT.md under
-- "Unclear / Requires Decision".
--
-- Compatibility notes:
--   * All clients talk to PostgREST with the ANON (publishable) key.
--     There is NO Supabase Auth session (auth.uid() is always NULL), so the
--     RLS baseline below is deliberately PERMISSIVE to keep the current app
--     working (the same policy the old schema.sql shipped). A recommended
--     hardening plan (role separation) is included at the bottom as comments
--     and detailed in REPORT.md.
--   * The file mirrors the existing style: CREATE TABLE IF NOT EXISTS,
--     ALTER TABLE ... ADD COLUMN IF NOT EXISTS, DROP POLICY before CREATE.
-- ============================================================================

begin;

-- ============================================================================
-- 1) TABLES
-- ============================================================================

-- ---------------------------------------------------------------------------
-- students — Student code (CREV-100x) + password login + parent PIN.
-- Mapped in repository.js: rowToStudent / studentToRow.
-- ---------------------------------------------------------------------------
create table if not exists public.students (
  id          text primary key,          -- e.g. CREV-1006 (generated client-side)
  name        text not null,
  stage       text not null,
  grade       text not null,
  parent_phone text not null,
  status      text not null default 'Active',
  password    text not null,             -- 6-digit login password
  parent_pin  text not null,             -- 4-digit parent login PIN
  created_at  date not null default current_date
);

create index if not exists students_stage_grade_idx on public.students (stage, grade);
create index if not exists students_status_idx    on public.students (status);
create index if not exists students_parent_pin_idx on public.students (parent_pin);

-- ---------------------------------------------------------------------------
-- teachers — Custom (non-Supabase) login: username/password stored here.
-- SECURITY DEFINER RPCs rotate `session_token` on login.
-- Mapped in repository.js: rowToTeacher / teacherToRow.
-- ---------------------------------------------------------------------------
create table if not exists public.teachers (
  id       text primary key,             -- T-001 ... (or admin-provided / UUID)
  name     text not null,
  subject  text not null default '',     -- primary subject (legacy single value)
  phone    text not null default '',
  status   text not null default 'Active',
  username text not null default '',
  password text not null default '',     -- plaintext today; RPCs hide it from SELECT
  subjects jsonb not null default '[]'::jsonb,  -- admin-granted teaching permissions
  stages   jsonb not null default '[]'::jsonb,
  grades   jsonb not null default '[]'::jsonb,
  session_token text not null default '' -- rotated on every teacher_login
);

-- Backfill for DBs created before these columns existed (idempotent):
alter table public.teachers add column if not exists username text not null default '';
alter table public.teachers add column if not exists password text not null default '';
alter table public.teachers add column if not exists subjects jsonb not null default '[]'::jsonb;
alter table public.teachers add column if not exists stages   jsonb not null default '[]'::jsonb;
alter table public.teachers add column if not exists grades   jsonb not null default '[]'::jsonb;
alter table public.teachers add column if not exists session_token text not null default '';

create unique index if not exists teachers_username_uidx on public.teachers (username);
create index if not exists teachers_status_idx    on public.teachers (status);
create index if not exists teachers_session_idx   on public.teachers (session_token);

-- ---------------------------------------------------------------------------
-- subjects — Admin-managed subject catalog. teachers_count/exams_count are
-- pre-computed display counters the app writes (NOT live aggregates).
-- ---------------------------------------------------------------------------
create table if not exists public.subjects (
  id            text primary key,        -- SUB-xx
  name          text not null unique,
  teachers_count int not null default 0,
  exams_count   int not null default 0
);

-- ---------------------------------------------------------------------------
-- classes — One row per grade/stage. LIVE app only inserts `name`
-- (repository.js classToRow → `{ name }`), and the repo documents that on the
-- live DB `id` is a DB-generated UUID. `stage` + counts are still READ by the
-- app (rowToClass / Classes page). Newly inserted classes therefore carry an
-- empty `stage` until the app is changed to also send it — see REPORT.md.
-- ---------------------------------------------------------------------------
create table if not exists public.classes (
  id             uuid primary key default gen_random_uuid(),
  stage          text not null default '',
  name           text not null,
  students_count int not null default 0,
  exams_count    int not null default 0
);

-- NOTE: NOT unique — the demo loader plain-inserts classes (fresh UUID each
-- time, no upsert), so repeated demo loads would violate a unique (stage,name).
create index if not exists classes_stage_name_idx on public.classes (stage, name);

-- ---------------------------------------------------------------------------
-- exams — Questions stored as JSONB so one row = one exam. Ownership via
-- `teacher_id`/`teacher_name`. Admin-created exams send teacher_id = '' (the
-- app's sentinel), so a hard FK to teachers is deliberately NOT enforced yet
-- (see REPORT.md / recommended FK at the bottom).
-- ---------------------------------------------------------------------------
create table if not exists public.exams (
  id               text primary key,     -- EX-001 (generated client-side)
  name             text not null,
  subject          text not null,
  stage            text not null,
  grade            text not null,
  duration_minutes int not null default 30,
  status           text not null default 'Draft',          -- Draft | Published
  created_at       text not null default to_char(now(), 'YYYY-MM-DD'),
  scheduled_date   text not null default '',
  start_time       text not null default '',
  end_time         text not null default '',
  instructions     text not null default '',
  pass_score       int not null default 0,
  archived         boolean not null default false,
  questions        jsonb not null default '[]'::jsonb,
  teacher_id       text not null default '',
  teacher_name     text not null default ''
);

-- Backfill (idempotent):
alter table public.exams add column if not exists pass_score      int not null default 0;
alter table public.exams add column if not exists archived       boolean not null default false;
alter table public.exams add column if not exists questions      jsonb not null default '[]'::jsonb;
alter table public.exams add column if not exists instructions   text not null default '';
alter table public.exams add column if not exists scheduled_date text not null default '';
alter table public.exams add column if not exists start_time     text not null default '';
alter table public.exams add column if not exists end_time       text not null default '';
alter table public.exams add column if not exists teacher_id     text not null default '';
alter table public.exams add column if not exists teacher_name   text not null default '';

create index if not exists exams_teacher_id_idx on public.exams (teacher_id);
create index if not exists exams_stage_grade_idx on public.exams (stage, grade);
create index if not exists exams_status_idx      on public.exams (status);

-- ---------------------------------------------------------------------------
-- exam_attempts — One row per graded submission (pre-graded client-side).
-- `answers` JSONB deliberately carries correct-answer fields (the TEACHER
-- review UI renders them). Access must therefore be restricted — the student
-- front-end must never read this column for an in-progress exam.
-- FKs: exam_id → exams (CASCADE so deleting an exam removes its attempts,
-- matching current app behavior); student_id → students (CASCADE).
-- ---------------------------------------------------------------------------
create table if not exists public.exam_attempts (
  id           text primary key,         -- AT-xxxx (generated client-side)
  exam_id      text not null references public.exams (id) on delete cascade,
  exam_name    text not null,
  subject      text not null,
  grade        text not null,
  student_id   text not null references public.students (id) on delete cascade,
  student_name text not null,
  submitted_at text not null,            -- 'YYYY-MM-DD HH:MM' (UTC)
  score        int not null default 0,
  total_score  int not null default 0,
  pass_score   int not null default 0,
  passed       boolean not null default false,
  answers      jsonb not null default '[]'::jsonb
);

create index if not exists exam_attempts_exam_id_idx   on public.exam_attempts (exam_id);
create index if not exists exam_attempts_student_idx   on public.exam_attempts (student_id);
create index if not exists exam_attempts_submitted_idx on public.exam_attempts (submitted_at);
-- One attempt per student per exam is a CURRENT APP RULE (findExamAttempt).
-- A unique index is RECOMMENDED but only after old duplicate data is cleaned:
-- create unique index if not exists exam_attempts_student_exam_uidx
--   on public.exam_attempts (student_id, exam_id);

-- ============================================================================
-- 2) FUNCTIONS / RPCs  (all SECURITY DEFINER — validated & scoped server-side)
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Internal permission normalizer (used by the RPCs below; NOT callable by
-- anon — execute revoked). Handles real jsonb arrays AND the JSON-encoded /
-- double-encoded / CSV text values the app has historically stored.
-- ---------------------------------------------------------------------------
create or replace function public._teacher_perm_values(p_raw text)
returns jsonb
language plpgsql
immutable
as $$
declare
  v_trim text := btrim(coalesce(p_raw, ''));
  v_json jsonb;
  v_elem jsonb;
  v_out  jsonb := '[]'::jsonb;
begin
  if v_trim = '' then
    return '[]'::jsonb;
  end if;

  if left(v_trim, 1) = '''' then
    v_trim := btrim(substr(v_trim, 2, greatest(length(v_trim) - 2, 0)));
  end if;
  if v_trim = '' then
    return '[]'::jsonb;
  end if;

  if left(v_trim, 1) in ('[', '"') then
    begin
      v_json := v_trim::jsonb;
    exception when others then
      v_json := null;
    end;
    if v_json is not null then
      if jsonb_typeof(v_json) = 'array' then
        for v_elem in select * from jsonb_array_elements(v_json)
        loop
          if jsonb_typeof(v_elem) = 'string' then
            v_out := v_out || public._teacher_perm_values(v_elem #>> '{}');
          end if;
        end loop;
        return v_out;
      end if;
      if jsonb_typeof(v_json) = 'string' then
        return public._teacher_perm_values(v_json #>> '{}');
      end if;
    end if;
  end if;

  v_trim := replace(v_trim, '،', ',');
  return to_jsonb(array_remove(string_to_array(v_trim, ','), ''));
end;
$$;

revoke all on function public._teacher_perm_values(text) from public;

-- ---------------------------------------------------------------------------
-- teacher_login(p_username, p_password)
--   Called as: supabase.rpc('teacher_login', { p_username, p_password })
--   The app expects an ARRAY (data.length / data[0] used) — hence RETURNS TABLE.
--   Rotates session_token; never returns the password column.
-- ---------------------------------------------------------------------------
create or replace function public.teacher_login(
  p_username text,
  p_password text
)
returns table (
  id            text,
  name          text,
  subject       text,
  subjects      jsonb,
  stages        jsonb,
  grades        jsonb,
  phone         text,
  username      text,
  status        text,
  session_token text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_teacher public.teachers%rowtype;
  v_token   text;
begin
  select * into v_teacher
  from public.teachers t
  where t.username = p_username
    and t.password = p_password
    and t.status = 'Active'
  limit 1;

  if v_teacher.id is null then
    return;
  end if;

  v_token := md5(gen_random_uuid()::text || gen_random_uuid()::text);

  update public.teachers
     set session_token = v_token
   where id = v_teacher.id;

  return query
    select v_teacher.id, v_teacher.name, v_teacher.subject,
           public._teacher_perm_values(v_teacher.subjects::text),
           public._teacher_perm_values(v_teacher.stages::text),
           public._teacher_perm_values(v_teacher.grades::text),
           v_teacher.phone, v_teacher.username, v_teacher.status,
           v_token;
end;
$$;

grant execute on function public.teacher_login(text, text) to anon;

-- ---------------------------------------------------------------------------
-- teacher_scoped_students(p_teacher_id, p_session_token)
--   Called as: supabase.rpc('teacher_scoped_students', { p_teacher_id, p_session_token })
--   Returns ONLY students whose stage AND grade are inside the teacher's
--   admin-granted permissions. `password` IS returned (the teacher dashboard
--   prints each student's login password for distribution).
-- ---------------------------------------------------------------------------
create or replace function public.teacher_scoped_students(
  p_teacher_id   text,
  p_session_token text
)
returns table (
  id           text,
  name         text,
  stage        text,
  grade        text,
  parent_phone text,
  status       text,
  password     text,
  created_at   date
)
language sql
security definer
set search_path = public
as $$
  select s.id, s.name, s.stage, s.grade, s.parent_phone, s.status, s.password, s.created_at
  from public.students s
  join public.teachers t
    on t.id = p_teacher_id
   and t.session_token = p_session_token
   and t.status = 'Active'
  where jsonb_array_length(public._teacher_perm_values(t.stages::text)) > 0
    and jsonb_array_length(public._teacher_perm_values(t.grades::text)) > 0
    and public._teacher_perm_values(t.stages::text) ? s.stage
    and public._teacher_perm_values(t.grades::text) ? s.grade
  order by s.name;
$$;

grant execute on function public.teacher_scoped_students(text, text) to anon;

-- ---------------------------------------------------------------------------
-- teacher_scoped_exams(p_teacher_id, p_session_token)
--   Called as: supabase.rpc('teacher_scoped_exams', { p_teacher_id, p_session_token })
--   Returns only the teacher's OWN exams whose subject/stage/grade are inside
--   the admin-granted permissions. Empty permission list = unrestricted for
--   that dimension (matches the app's JS scoping).
-- ---------------------------------------------------------------------------
create or replace function public.teacher_scoped_exams(
  p_teacher_id   text,
  p_session_token text
)
returns table (
  id               text,
  name             text,
  subject          text,
  stage            text,
  grade            text,
  duration_minutes int,
  status           text,
  created_at       text,
  scheduled_date   text,
  start_time       text,
  end_time         text,
  instructions     text,
  pass_score       int,
  archived         boolean,
  questions        jsonb,
  teacher_id       text,
  teacher_name     text
)
language sql
security definer
set search_path = public
as $$
  select e.id, e.name, e.subject, e.stage, e.grade, e.duration_minutes,
         e.status, e.created_at, e.scheduled_date, e.start_time, e.end_time,
         e.instructions, e.pass_score, e.archived, e.questions,
         e.teacher_id, e.teacher_name
  from public.exams e
  join public.teachers t
    on t.id = p_teacher_id
   and t.session_token = p_session_token
   and t.status = 'Active'
  where e.teacher_id = p_teacher_id
    and (jsonb_array_length(public._teacher_perm_values(t.subjects::text)) = 0
         or public._teacher_perm_values(t.subjects::text) ? e.subject)
    and (jsonb_array_length(public._teacher_perm_values(t.stages::text)) = 0
         or public._teacher_perm_values(t.stages::text) ? e.stage)
    and (jsonb_array_length(public._teacher_perm_values(t.grades::text)) = 0
         or public._teacher_perm_values(t.grades::text) ? e.grade)
  order by e.created_at desc;
$$;

grant execute on function public.teacher_scoped_exams(text, text) to anon;

-- ---------------------------------------------------------------------------
-- teacher_scoped_attempts(p_teacher_id, p_session_token)
--   Called as: supabase.rpc('teacher_scoped_attempts', { p_teacher_id, p_session_token })
--   Returns results submitted ONLY on the teacher's own in-scope exams.
-- ---------------------------------------------------------------------------
create or replace function public.teacher_scoped_attempts(
  p_teacher_id   text,
  p_session_token text
)
returns table (
  id           text,
  exam_id      text,
  exam_name    text,
  subject      text,
  grade        text,
  student_id   text,
  student_name text,
  submitted_at text,
  score        int,
  total_score  int,
  pass_score   int,
  passed       boolean,
  answers      jsonb
)
language sql
security definer
set search_path = public
as $$
  select a.id, a.exam_id, a.exam_name, a.subject, a.grade, a.student_id,
         a.student_name, a.submitted_at, a.score, a.total_score,
         a.pass_score, a.passed, a.answers
  from public.exam_attempts a
  join public.exams e on e.id = a.exam_id
  join public.teachers t
    on t.id = p_teacher_id
   and t.session_token = p_session_token
   and t.status = 'Active'
  where e.teacher_id = p_teacher_id
    and (jsonb_array_length(public._teacher_perm_values(t.subjects::text)) = 0
         or public._teacher_perm_values(t.subjects::text) ? e.subject)
    and (jsonb_array_length(public._teacher_perm_values(t.stages::text)) = 0
         or public._teacher_perm_values(t.stages::text) ? e.stage)
    and (jsonb_array_length(public._teacher_perm_values(t.grades::text)) = 0
         or public._teacher_perm_values(t.grades::text) ? e.grade)
  order by a.submitted_at desc;
$$;

grant execute on function public.teacher_scoped_attempts(text, text) to anon;

-- ---------------------------------------------------------------------------
-- student_login(p_student_id, p_password)
--   Called as: supabase.rpc('student_login', { p_student_id, p_password })
--   App uses data[0]; returns ONLY non-secret student fields.
-- ---------------------------------------------------------------------------
create or replace function public.student_login(
  p_student_id text,
  p_password   text
)
returns table (
  id           text,
  name         text,
  stage        text,
  grade        text,
  status       text,
  parent_phone text
)
language sql
security definer
set search_path = public
as $$
  select s.id, s.name, s.stage, s.grade, s.status, s.parent_phone
  from public.students s
  where s.id = p_student_id
    and s.password = p_password
    and s.status = 'Active'
  limit 1;
$$;

grant execute on function public.student_login(text, text) to anon;

-- ---------------------------------------------------------------------------
-- parent_login(p_pin)
--   Called as: supabase.rpc('parent_login', { p_pin })
--   App requires EXACTLY ONE match (limit 2 lets the app detect duplicates).
--   There is NO separate parents table today — a PIN belongs to one student.
-- ---------------------------------------------------------------------------
create or replace function public.parent_login(
  p_pin text
)
returns table (
  id           text,
  name         text,
  stage        text,
  grade        text,
  status       text,
  parent_phone text
)
language sql
security definer
set search_path = public
as $$
  select s.id, s.name, s.stage, s.grade, s.status, s.parent_phone
  from public.students s
  where s.parent_pin = p_pin
    and s.status = 'Active'
  limit 2;
$$;

grant execute on function public.parent_login(text) to anon;

-- ============================================================================
-- 3) ROW LEVEL SECURITY
--
-- BASELINE (keeps the current anon-key app fully working):
--   All traffic uses the anon/publishable key. There is no Supabase Auth
--   session, so auth.uid() is always NULL and PostgREST cannot tell an admin
--   request from a student request. The baseline therefore keeps the permissive
--   demo policies (identical to the old schema.sql) + a column-level revoke on
--   the student secret columns.
--
-- This means: row-LEVEL role separation (student can't read other students,
-- teacher can't read other teachers' data) CANNOT be enforced purely with RLS
-- until one of the options in REPORT.md ("Unclear / Requires Decision") is
-- chosen (Supabase Auth, or moving every read/write behind SECURITY DEFINER
-- RPCs, or a request-scoped session header). Until then, scoping is enforced
-- ONLY inside the SECURITY DEFINER RPCs + JS-side filters.
-- ============================================================================

alter table public.students      enable row level security;
alter table public.teachers      enable row level security;
alter table public.subjects      enable row level security;
alter table public.classes       enable row level security;
alter table public.exams         enable row level security;
alter table public.exam_attempts enable row level security;

drop policy if exists "students read/write" on public.students;
create policy "students read/write"
  on public.students for all using (true) with check (true);

drop policy if exists "teachers read/write" on public.teachers;
create policy "teachers read/write"
  on public.teachers for all using (true) with check (true);

drop policy if exists "subjects read/write" on public.subjects;
create policy "subjects read/write"
  on public.subjects for all using (true) with check (true);

drop policy if exists "classes read/write" on public.classes;
create policy "classes read/write"
  on public.classes for all using (true) with check (true);

drop policy if exists "exams read/write" on public.exams;
create policy "exams read/write"
  on public.exams for all using (true) with check (true);

drop policy if exists "exam_attempts read/write" on public.exam_attempts;
create policy "exam_attempts read/write"
  on public.exam_attempts for all using (true) with check (true);

-- Column-level protection for student credentials: anon can no longer SELECT
-- password / parent_pin directly. Login flows go through the SECURITY DEFINER
-- RPCs (student_login / parent_login), and the teacher scoping RPC returns the
-- password only to a verified teacher.
revoke select (password, parent_pin) on public.students from anon;

-- Explicit grants (Supabase's default template already grants these, kept here
-- for a fresh-project run).
grant usage on schema public to anon;
grant select, insert, update, delete on public.students, public.teachers,
      public.subjects, public.classes, public.exams, public.exam_attempts to anon;

-- ============================================================================
-- 4) RECOMMENDED HARDENING — REQUIRES A DECISION (NOT applied here)
--
-- These blocks are COMMENTED OUT because they break the current anon-key app.
-- Full rationale in REPORT.md → "Unclear / Requires Decision". The three
-- viable paths (choose ONE):
--   (A) Move to Supabase Auth for all four roles, then use auth.uid() +
--       a `profiles`/roles table and real row-level policies.
--   (B) Keep custom sessions (like the teacher session_token) but expose
--       EVERY read/write through SECURITY DEFINER RPCs and REVOKE direct table
--       access from anon entirely.
--   (C) Split the anon key's power: keep permissive policies ONLY on tables
--       the admin genuinely needs (subjects/classes/…), and serve student/
--       parent/teacher reads exclusively via RPCs (the app already does the
--       latter for teachers; student/parent pages still read the shared cache).
--
-- Under (A) or (B) the intended matrix is:
--   students        SELECT: self / own teacher / own parent / admin
--                   INSERT/UPDATE/DELETE: admin only
--   teachers        SELECT: self / admin (never password for anon)
--                   INSERT/UPDATE/DELETE: admin only
--   subjects        SELECT: all authenticated   INSERT/UPDATE/DELETE: admin
--   classes         SELECT: all authenticated   INSERT/UPDATE/DELETE: admin
--   exams           SELECT: owner teacher / eligible student / admin
--                   INSERT/UPDATE/DELETE: owner teacher / admin
--   exam_attempts   SELECT: owning teacher / the student / parent of that
--                   student / admin   INSERT: student (their own submit, via RPC)
--                   DELETE: owning teacher / admin
--   exams.questions — the answers jsonb MUST be stripped before it reaches a
--   student (student exam page must never receive correctIndex/correctAnswer).
--
-- Example (option A sketch, NOT active):
--   revoke select, insert, update, delete on public.exam_attempts from anon;
--   create policy "attempts self select"
--     on public.exam_attempts for select using (student_id = auth.uid()::text);
-- ============================================================================

commit;
